### ISSUE TITLE
Check for Presence of mb_convert_encoding

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieauth#156]
Fatal error: Uncaught Error: Call to undefined function mb_convert_encoding() in /var/www/html/s.ragavan.co/public_html/wp-content/plugins/indieauth/includes/class-indieauth-client-discovery.php:113 Stack trace: #0 /var/www/html/s.ragavan.co/public_html/wp-content/plugins/indieauth/includes/class-indieauth-client-discovery.php(51): IndieAuth_Client_Discovery::extract_client_data_from_html('<!doctype html>...', 'https://indieau...') #1 /var/www/html/s.ragavan.co/public_html/wp-content/plugins/indieauth/includes/class-indieauth-client-discovery.php(12): IndieAuth_Client_Discovery->parse('https://indieau...') #2 /var/www/html/s.ragavan.co/public_html/wp-content/plugins/indieauth/includes/class-indieauth-authorization-endpoint.php(210): IndieAuth_Client_Discovery->__construct('https://indieau...') #3 /var/www/html/s.ragavan.co/public_html/wp-content/plugins/indieauth/includes/class-indieauth-authorization-endpoint.php(199): IndieAuth_Authorization_Endpoint->authorize() #4 /var/www/html/s.ragavan.co/public_html/wp-includes/cla in /var/www/html/s.ragavan.co/public_html/wp-content/plugins/indieauth/includes/class-indieauth-client-discovery.php on line 113

**Comment by dshanske** [comment]
https://github.com/symfony/polyfill-mbstring
