### ISSUE TITLE
Fatal Error when attempting to post via micropub

### ISSUE THREAD

**Issue by idallas** [indieweb/wordpress-indieauth#45]
When attempting to create a post via micropub, I'm seeing this PHP Fatal Error:

```
[30-Apr-2018 23:36:01 UTC] PHP Fatal error:  Uncaught Error: Call to a member function using_index_permalinks() on null in /wordpress/wp-includes/rest-api.php:313
Stack trace:
#0 /wordpress/wp-includes/rest-api.php(375): get_rest_url(NULL, '/indieauth/1.0/...', 'json')
#1 /wordpress/wp-content/plugins/indieauth/includes/functions.php(286): rest_url('/indieauth/1.0/...')
#2 /wordpress/wp-content/plugins/indieauth/includes/class-indieauth-authenticate.php(119): get_indieauth_token_endpoint()
#3 /wordpress/wp-content/plugins/indieauth/includes/class-indieauth-authenticate.php(99): IndieAuth_Authenticate->verify_access_token('...')
#4 /wordpress/wp-includes/class-wp-hook.php(286): IndieAuth_Authenticate->determine_current_user(NULL)
#5 /wordpress/wp-includes/plugin.php(203): WP_Hook->apply_filters(NULL, Array)
#6 /wordpress/wp-includes/user.php(2603): ap in /wordpress/wp-includes/rest-api.php on line 313
```
It seems like $wp_rewrite hasn't yet been defined by this point in the request.  I'm using micropub.rocks to test this.  Am I doing something wrong?

**Comment by dshanske** [comment]
That is odd, because I have it on 3 sites.  Do you have any plugins that might disable the REST API?

**Comment by idallas** [comment]
Aha!  I should have tried that before... deactivating the Jetpack plugin resolves the issue.  Any ideas why there would be a conflict with that?

**Comment by dshanske** [comment]
I am not sure, but I can test this.

**Comment by Ruxton** [comment]
which cascades to another issue in that plugins_loaded is fired before global wp_rewrite is loaded

```
 PHP Fatal error:  Call to a member function wp_rewrite_rules() on a non-object in public_html/wp-content/plugins/indieauth/includes/functions.php on line 163
```

**Comment by dshanske** [comment]
Thanks for figuring that out.

**Comment by dshanske** [comment]
I am going to try and change how the plugin is activated and see about the order

**Comment by dshanske** [comment]
I think I have a solution for this

**Comment by dshanske** [comment]
This should hopefully be resolved with the latest merge.

**Comment by dshanske** [comment]
Is this resolved?

**Comment by dshanske** [comment]
Thanks
